FROM mcr.microsoft.com/azureml/curated/acpt-pytorch-2.0-cuda11.7

RUN pip install accelerate==0.19.0 \
                datasets==2.11.0 \
                evaluate==0.4.0 \
                nltk \
                rouge_score \
                transformers==4.29.2 \
                optimum==1.8.6