FROM mcr.microsoft.com/azureml/aifx/stable-ubuntu2004-cu115-py38-torch1110

RUN python -m pip install accelerate \
                        torch >= 1.3 \
                        datasets >= 1.8.0 \
                        sentencepiece != 0.1.92 \
                        protobuf \
                        sacrebleu >= 1.4.12 \
                        py7zr \
                        git+https://github.com/huggingface/optimum.git \
                        transformers==4.16.0
