FROM mcr.microsoft.com/azureml/aifx/stable-ubuntu2004-cu115-py38-torch1110

RUN python -m pip install \
                        torch>=1.9.0 \
                        datasets>=1.8.0 \
                        sentencepiece>0.1.92 \
                        optimum==1.2.3 \
                        transformers==4.16.0 \
                        torch-ort

RUN pip uninstall -y mlflow-skinny
